### ISSUE TITLE
Dcore can`t fing TRIQS libraries

### ISSUE THREAD

**Issue by MikhailFrolov-cyber** [issp-center-dev/DCore#137]
Dear developers
I have installed Dcore and everything was fine. No mistakes or issues was in procces, But when I try to use command dcore_pre dmft_s              quare.ini it gives:
triqs_dft_tools is not installed!
We can use a TRIQS-compatible library instead by setting environment variable DCORE_TRIQS_COMPAT to 1.
Traceback (most recent call last):
  File "/home/users/py/mfrolov/anaconda3/envs/dmft/bin/dcore_pre", line 5, in <module>
    from dcore.dcore_pre import run
  File "/home/users/py/mfrolov/anaconda3/envs/dmft/lib/python3.9/site-packages/d core/dcore_pre.py", line 24, in <module>
    from dcore._dispatcher import HDFArchive
  File "/home/users/py/mfrolov/anaconda3/envs/dmft/lib/python3.9/site-packages/dcore/_dispatcher.py", line 25, in <module>
    raise RuntimeError("TRIQS is not found!")
RuntimeError: TRIQS is not found!

But TRIQS and triqs_dft_tools was instaleted. Can you tell me where does the program indicate where to look for TRIQS and triqs_dft_tools? Maybe it's just worth manually prescribing it.

**Comment by MikhailFrolov-cyber** [comment]
Yes I have done this steps. I`ve re-install triqs_dft_tools and it works. But now when I use dcore -np 2 dmft.ini I get:
RuntimeError: Error occurred while executing MPI program!
In output file this message appears: 
AssertionError: Type of indices incorrect : should be None, Gfindices, list of str, or list of list of str
Unexpected error: Type of indices incorrect : should be None, Gfindices, list of str, or list of list of str
 I have installed again open mpi using conda install -c conda-forge openmpi but still mistake is happening.

**Comment by shinaoka** [comment]
Hi, I need more information.
What impurity solver did you use?
* Do you have TRIQS (probably from anaconda) installed on your system?

**Comment by MikhailFrolov-cyber** [comment]
Well I try to use CTHYB TRIQS solver but now dcore gives me this massage when I use command dcore_pre dmft.ini:
Traceback (most recent call last):
  File "/home/users/py/mfrolov/anaconda3/envs/dcore/bin/dcore_pre", line 5, in <module>
    from dcore.dcore_pre import run
  File "/home/users/py/mfrolov/anaconda3/envs/dcore/lib/python3.12/site-packages/dcore/dcore_pre.py", line 24, in <module>
    from dcore._dispatcher import HDFArchive
  File "/home/users/py/mfrolov/anaconda3/envs/dcore/lib/python3.12/site-packages/dcore/_dispatcher.py", line 22, in <module>
    if not importlib.util.find_spec(l):
           ^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'util'

**Comment by DFTsher** [comment]
I guess the main problem here was to use approprieate version of Trqis and some packages of python 3.
